<?php 
		require(dirname(dirname(__FILE__))."/core/model/entity/calendar.php");
		require(dirname(dirname(__FILE__))."/core/model/entity/colors.php");
		
			require(dirname(dirname(__FILE__))."/core/model/entity/card.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/company.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/company_user.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/media.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/permission.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/role.php");
			require(dirname(dirname(__FILE__))."/core/model/entity/user.php");
			require(dirname(dirname(__FILE__))."/core/model/table/cards.php");
			require(dirname(dirname(__FILE__))."/core/model/table/companies.php");
			require(dirname(dirname(__FILE__))."/core/model/table/medias.php");
			require(dirname(dirname(__FILE__))."/core/model/table/permissions.php");
			require(dirname(dirname(__FILE__))."/core/model/table/roles.php");
			require(dirname(dirname(__FILE__))."/core/model/table/users.php");
			require(dirname(dirname(__FILE__))."/model/entity/category.php");
			require(dirname(dirname(__FILE__))."/model/entity/product.php");
			require(dirname(dirname(__FILE__))."/model/entity/product_store.php");
			require(dirname(dirname(__FILE__))."/model/entity/store.php");
			require(dirname(dirname(__FILE__))."/model/table/categories.php");
			require(dirname(dirname(__FILE__))."/model/table/products.php");
			require(dirname(dirname(__FILE__))."/model/table/stores.php");
			 ?>